### ISSUE TITLE
ValueError: No op named NonMaxSuppressionV2 in defined operations.

### ISSUE THREAD

**Issue by steffiand** [Nirvan101/Person-Re-identification#12]
Traceback (most recent call last):
  File "human_detect_track2.py", line 158, in <module>
    odapi = DetectorAPI(path_to_ckpt=model_path)
  File "human_detect_track2.py", line 27, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "C:\Users\Steffi Andrade\.conda\envs\trial\lib\site-packages\tensorflow\python\framework\importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named NonMaxSuppressionV2 in defined operations.

I am getting the above error when i run the 'human_detect_track2.py' file. i am using tensorflow=1.2.1 as mentioned in https://github.com/digitalbrain79/person-reid

please suggest how i can resolve this error?

**Comment by steffiand** [comment]
Can you please mention the tensorflow version you worked on for 'human_detect_track2.py' to work?
