### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'

### ISSUE THREAD

**Issue by MohitMourya** [Nirvan101/Person-Re-identification#14]
```
2021-02-08 12:02:10.918094: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Build network
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run.py", line 135, in main
    logits = network(images1, images2, weight_decay)
  File "run.py", line 58, in network
    kernel_regularizer=tf.contrib.layers.l2_regularizer(weight_decay), name='conv1_1')
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'
```

**Comment by MohitMourya** [comment]
Manually upgraded tf1 code to tf2
