### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Nagaraj4896** [Nirvan101/Person-Re-identification#8]
Traceback (most recent call last):
  File "human_detect_track3.py", line 215, in <module>
    odapi.find(img, boxes_cur,boxes_prev, box )
  File "human_detect_track3.py", line 95, in find
    boxes_cur[ int(folder) ][0] = box
IndexError: list index out of range

**Comment by grasulkhuja** [comment]
Hi, I solve this problem. First of all, you should install Ubuntu 18.04 LTS. After then, python 2.7, Cuda- toolkit v10.2 with cuDNN capability with Cuda-toolkit, IDE(I'm using PyCharm and create virtual env with python 2.7). Install there OpenCV-python and TensorFlow v1.12.2

**Comment by ManoharSai2000** [comment]
Same Problem here??

**Comment by Malavika811** [comment]
Facing Same issue

**Comment by Hrishikesh1213** [comment]
> Facing Same issue

are you  able to solve it?
